apiVersion: v1
kind: Service
metadata:
  name: gezag
  labels:
    app: gezag
spec:
  selector:
    name: gezag
  type: LoadBalancer
  ports:
    - name: "5130"
      port: 5130
      targetPort: http-gezag
