openapi: 3.1.0
info:
  title: meerderjarige type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    Meerderjarige:
      type: object
      properties:
        burgerservicenummer:
          $ref: '../../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        naam:
          $ref: '../../brp/naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
        geslacht:
          $ref: '../../brp/geslacht/geslachtsaanduiding-v1.yaml#/components/schemas/Geslachtsaanduiding'
