services:

  gezagmock:
    container_name: gezagmock
    image: ghcr.io/brp-api/gezag-mock:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5020
      - Ecs__Path=/var/log/gezag-mock.json
    ports:
      - "5020:5020"
    volumes:
      - ../test-data/GezagMock/test-data.json:/app/Data/test-data.json
      - ../test-data/logs:/var/log
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
