services:
  haalcentraal_api:
    image: ghcr.io/brp-api/personen-data-service:2.3.0-202408281540
    environment:
      - Database__Host=postgres
      - Database__Username=root
      - Database__Password=root
      - Database__Database=rvig_haalcentraal_testdata
      - HaalcentraalApi__MaxSearchResults=10
      - ASPNETCORE_URLS=http://+;
      - Serilog__MinimumLevel__Default=Information
      - WebApi__Url=http://gezagmock:5020/api/v1
      - ProtocolleringAuthorization__UseAuthorizationChecks=false
      - ProtocolleringAuthorization__UseProtocollering=false
      - Ecs__Path=/var/log/personen-data-service.json
      - Ecs__FileSizeLimitBytes=1048576
      # - Ecs__RetainedFileCountLimit=5
    ports:
      - "8000:80"
    volumes:
      - ../test-data/logs:/var/log
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
