using Rvig.HaalCentraalApi.Shared.Fields;

namespace Rvig.HaalCentraalApi.Personen.Fields;

public class PersonenFieldsSettings : FieldsSettings
{
	public override FieldsSettingsModel GbaFieldsSettings { get; }

	public PersonenFieldsSettings()
	{
		GbaFieldsSettings = InitGbaFieldsSettings();
	}

	protected override FieldsSettingsModel InitGbaFieldsSettings()
	{
		return new FieldsSettingsModel("fields")
		{
			ForbiddenProperties = new List<string>()
			{
				"geheimhoudingPersoonsgegevens", "rni", "persoonInOnderzoek", "gezagInOnderzoek",
				"inOnderzoek", "opschortingBijhouding", "verificatie", "kinderen.inOnderzoek", "ouders.inOnderzoek",
				"partners.inOnderzoek", "nationaliteiten.inOnderzoek", "overlijden.inOnderzoek", "verblijfplaats.inOnderzoek",
				"verblijfstitel.inOnderzoek", "immigratie.inOnderzoek"
			},
			PropertiesToDiscard = new List<string>(),
			MandatoryProperties = new List<string>
			{
				"geheimhoudingPersoonsgegevens", "opschortingBijhouding",
				"persoonInOnderzoek", "gezagInOnderzoek",
				"rni",
				"verificatie"
			},
			SetChildPropertiesIfExistInScope = new Dictionary<string, string>
			{
				{ "kinderen.inOnderzoek", "kinderen" },  { "ouders.inOnderzoek", "ouders" }, { "partners.inOnderzoek", "partners" },
				{ "nationaliteiten.inOnderzoek", "nationaliteiten" }, { "overlijden.inOnderzoek", "overlijden" }, { "verblijfplaats.inOnderzoek", "verblijfplaats" }, { "verblijfstitel.inOnderzoek", "verblijfstitel" }
			},
			SetPropertiesIfContextPropertyNotNull = new Dictionary<string, string>
			{
				{ "persoonInOnderzoek", "" }, { "persoonInOnderzoek.datumIngangOnderzoek", "persoonInOnderzoek" },
				{ "gezagInOnderzoek", "" }, { "gezagInOnderzoek.datumIngangOnderzoek", "gezagInOnderzoek" },
				{ "kinderen.inOnderzoek", "kinderen" }, { "kinderen.inOnderzoek.datumIngangOnderzoek", "kinderen.inOnderzoek" },
				{ "ouders.inOnderzoek", "ouders" }, { "ouders.inOnderzoek.datumIngangOnderzoek", "ouders.inOnderzoek" },
				{ "partners.inOnderzoek", "partners" }, { "partners.inOnderzoek.datumIngangOnderzoek", "partners.inOnderzoek" },
				{ "nationaliteiten.inOnderzoek", "nationaliteiten" }, { "nationaliteiten.inOnderzoek.datumIngangOnderzoek", "nationaliteiten.inOnderzoek" },
				{ "overlijden.inOnderzoek", "overlijden" }, { "overlijden.inOnderzoek.datumIngangOnderzoek", "overlijden.inOnderzoek" },
				{ "verblijfplaats.inOnderzoek", "verblijfplaats" },{ "verblijfplaats.inOnderzoek.datumIngangOnderzoek", "verblijfplaats.inOnderzoek" },
				{ "verblijfstitel.inOnderzoek", "verblijfstitel" }, { "verblijfstitel.inOnderzoek.datumIngangOnderzoek", "verblijfstitel.inOnderzoek" }
			},
			ShortHandMappings = new Dictionary<string, string>
			{
				// Proxy to GBA translation
				{ "naam", "naam&geslacht" },
				{ "adressering", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&gemeenteVanInschrijving&verblijfplaats.straat&verblijfplaats.huisnummer&verblijfplaats.huisletter&verblijfplaats.huisnummertoevoeging&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.postcode&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving&verblijfplaats.land&verblijfplaats.regel1&verblijfplaats.regel2&verblijfplaats.regel3&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adressering.aanhef", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adressering.aanschrijfwijze", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adressering.aanschrijfwijze.aanspreekvorm", "naam.adellijkeTitelPredicaat&naam.aanduidingNaamgebruik&geslacht&partners.naam.adellijkeTitelPredicaat&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adressering.aanschrijfwijze.naam", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adressering.adresregel1", "verblijfplaats.straat&verblijfplaats.huisnummer&verblijfplaats.huisletter&verblijfplaats.huisnummertoevoeging&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.locatiebeschrijving&verblijfplaats.land&verblijfplaats.regel1" },
				{ "adressering.adresregel2", "gemeenteVanInschrijving&verblijfplaats.straat&verblijfplaats.huisnummer&verblijfplaats.postcode&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving&verblijfplaats.land&verblijfplaats.regel2" },
				{ "adressering.adresregel3", "verblijfplaats.land&verblijfplaats.regel3" },
				{ "adressering.gebruikInLopendeTekst", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adressering.land", "verblijfplaats.land&verblijfplaats.regel1&verblijfplaats.regel2&verblijfplaats.regel3" },
				{ "adressering.land.code", "verblijfplaats.land&verblijfplaats.regel1&verblijfplaats.regel2&verblijfplaats.regel3" },
				{ "adressering.land.omschrijving", "verblijfplaats.land&verblijfplaats.regel1&verblijfplaats.regel2&verblijfplaats.regel3" },
				{ "adresseringBinnenland", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&gemeenteVanInschrijving&verblijfplaats.straat&verblijfplaats.huisnummer&verblijfplaats.huisletter&verblijfplaats.huisnummertoevoeging&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.postcode&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adresseringBinnenland.aanhef", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adresseringBinnenland.aanschrijfwijze", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adresseringBinnenland.aanschrijfwijze.aanspreekvorm", "naam.adellijkeTitelPredicaat&naam.aanduidingNaamgebruik&geslacht&partners.naam.adellijkeTitelPredicaat&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adresseringBinnenland.aanschrijfwijze.naam", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "adresseringBinnenland.adresregel1", "verblijfplaats.straat&verblijfplaats.huisnummer&verblijfplaats.huisletter&verblijfplaats.huisnummertoevoeging&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.locatiebeschrijving&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.locatiebeschrijving" },
				{ "adresseringBinnenland.adresregel2", "gemeenteVanInschrijving&verblijfplaats.straat&verblijfplaats.huisnummer&verblijfplaats.postcode&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving" },
				{ "adresseringBinnenland.gebruikInLopendeTekst", "naam&geslacht&partners.naam.adellijkeTitelPredicaat&partners.naam.voorvoegsel&partners.naam.geslachtsnaam&partners.aangaanHuwelijkPartnerschap.datum&partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "immigratie.indicatieVestigingVanuitBuitenland", "immigratie.datumVestigingInNederland" },
				{ "immigratie.vanuitVerblijfplaatsOnbekend", "immigratie.landVanwaarIngeschreven" },
				{ "kinderen.naam.voorletters", "kinderen.naam.voornamen" },
				{ "leeftijd", "geboorte.datum" },
				{ "naam.volledigeNaam", "naam.voornamen&naam.adellijkeTitelPredicaat&naam.voorvoegsel&naam.geslachtsnaam&geslacht" },
				{ "naam.voorletters", "naam.voornamen" },
				{ "nationaliteiten.datumIngangGeldigheid", "nationaliteiten.datumIngangGeldigheid&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.nationaliteit", "nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.nationaliteit.code", "nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.nationaliteit.omschrijving", "nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.redenOpname", "nationaliteiten.redenOpname&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.redenOpname.code", "nationaliteiten.redenOpname&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.redenOpname.omschrijving", "nationaliteiten.redenOpname&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.type", "nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "ouders.naam.voorletters", "ouders.naam.voornamen" },
				{ "partners.naam.voorletters", "partners.naam.voornamen" },
				{ "verblijfplaats.datumVan", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.datumAanvangAdresBuitenland&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres", "verblijfplaats.straat&verblijfplaats.naamOpenbareRuimte&verblijfplaats.huisnummer&verblijfplaats.huisletter&verblijfplaats.huisnummertoevoeging&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.postcode&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving&verblijfplaats.land&verblijfplaats.regel1&verblijfplaats.regel2&verblijfplaats.regel3" },
				{ "verblijfplaats.verblijfadres.aanduidingBijHuisnummer", "verblijfplaats.straat&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.aanduidingBijHuisnummer.code", "verblijfplaats.straat&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.aanduidingBijHuisnummer.omschrijving", "verblijfplaats.straat&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.huisletter", "verblijfplaats.straat&verblijfplaats.huisletter&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.huisnummer", "verblijfplaats.straat&verblijfplaats.huisnummer&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.huisnummertoevoeging", "verblijfplaats.straat&verblijfplaats.huisnummertoevoeging&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.korteStraatnaam", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.land", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.land.code", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.land.omschrijving", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.locatiebeschrijving", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.postcode", "verblijfplaats.straat&verblijfplaats.postcode&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.regel1", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land&verblijfplaats.regel1" },
				{ "verblijfplaats.verblijfadres.regel2", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land&verblijfplaats.regel2" },
				{ "verblijfplaats.verblijfadres.regel3", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land&verblijfplaats.regel3" },
				{ "verblijfplaats.verblijfadres.officieleStraatnaam", "verblijfplaats.straat&verblijfplaats.naamOpenbareRuimte&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.verblijfadres.woonplaats", "verblijfplaats.straat&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumIngangGeldigheid", "verblijfplaats.datumIngangGeldigheid&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.functieAdres", "verblijfplaats.functieAdres&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.adresseerbaarObjectIdentificatie", "verblijfplaats.adresseerbaarObjectIdentificatie&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.nummeraanduidingIdentificatie", "verblijfplaats.nummeraanduidingIdentificatie&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.type", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.datumAanvangAdresBuitenland&verblijfplaats.datumIngangGeldigheid&verblijfplaats.functieAdres&verblijfplaats.adresseerbaarObjectIdentificatie&verblijfplaats.nummeraanduidingIdentificatie&verblijfplaats.straat&verblijfplaats.naamOpenbareRuimte&verblijfplaats.huisnummer&verblijfplaats.huisletter&verblijfplaats.huisnummertoevoeging&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.postcode&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving&verblijfplaats.land&verblijfplaats.regel1&verblijfplaats.regel2&verblijfplaats.regel3" },
				{ "verblijfplaatsBinnenland.verblijfadres.aanduidingBijHuisnummer", "verblijfplaats.straat&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.aanduidingBijHuisnummer.code", "verblijfplaats.straat&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.aanduidingBijHuisnummer.omschrijving", "verblijfplaats.straat&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.huisletter", "verblijfplaats.straat&verblijfplaats.huisletter&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.huisnummer", "verblijfplaats.straat&verblijfplaats.huisnummer&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.huisnummertoevoeging", "verblijfplaats.straat&verblijfplaats.huisnummertoevoeging&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.korteStraatnaam", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.locatiebeschrijving", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.postcode", "verblijfplaats.straat&verblijfplaats.postcode&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.officieleStraatnaam", "verblijfplaats.straat&verblijfplaats.naamOpenbareRuimte&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres.woonplaats", "verblijfplaats.straat&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.verblijfadres", "verblijfplaats.straat&verblijfplaats.naamOpenbareRuimte&verblijfplaats.huisnummer&verblijfplaats.huisletter&verblijfplaats.huisnummertoevoeging&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.postcode&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland.datumIngangGeldigheid", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.datumIngangGeldigheid" },
				{ "verblijfplaatsBinnenland.functieAdres", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.functieAdres" },
				{ "verblijfplaatsBinnenland.adresseerbaarObjectIdentificatie", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.adresseerbaarObjectIdentificatie" },
				{ "verblijfplaatsBinnenland.nummeraanduidingIdentificatie", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.nummeraanduidingIdentificatie" },
				{ "verblijfplaatsBinnenland.type", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving" },
				{ "verblijfplaatsBinnenland", "verblijfplaats.straat&verblijfplaats.naamOpenbareRuimte&verblijfplaats.huisnummer&verblijfplaats.huisletter&verblijfplaats.huisnummertoevoeging&verblijfplaats.aanduidingBijHuisnummer&verblijfplaats.postcode&verblijfplaats.woonplaats&verblijfplaats.locatiebeschrijving&verblijfplaats.nummeraanduidingIdentificatie&verblijfplaats.adresseerbaarObjectIdentificatie&verblijfplaats.functieAdres&verblijfplaats.datumIngangGeldigheid&verblijfplaats.datumAanvangAdreshouding" },
				{ "verblijfplaatsBinnenland.datumVan", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.straat&verblijfplaats.locatiebeschrijving" },

				// DATE FIELDS
				{ "datumEersteInschrijvingGBA.type", "datumEersteInschrijvingGBA" },
				{ "datumEersteInschrijvingGBA.langFormaat", "datumEersteInschrijvingGBA" },
				{ "datumEersteInschrijvingGBA.datum", "datumEersteInschrijvingGBA" },
				{ "datumEersteInschrijvingGBA.jaar", "datumEersteInschrijvingGBA" },
				{ "datumEersteInschrijvingGBA.maand", "datumEersteInschrijvingGBA" },
				{ "datumEersteInschrijvingGBA.onbekend", "datumEersteInschrijvingGBA" },

				{ "datumInschrijvingInGemeente.type", "datumInschrijvingInGemeente" },
				{ "datumInschrijvingInGemeente.langFormaat", "datumInschrijvingInGemeente" },
				{ "datumInschrijvingInGemeente.datum", "datumInschrijvingInGemeente" },
				{ "datumInschrijvingInGemeente.jaar", "datumInschrijvingInGemeente" },
				{ "datumInschrijvingInGemeente.maand", "datumInschrijvingInGemeente" },
				{ "datumInschrijvingInGemeente.onbekend", "datumInschrijvingInGemeente" },

				{ "geboorte.datum.type", "geboorte.datum" },
				{ "geboorte.datum.langFormaat", "geboorte.datum" },
				{ "geboorte.datum.datum", "geboorte.datum" },
				{ "geboorte.datum.jaar", "geboorte.datum" },
				{ "geboorte.datum.maand", "geboorte.datum" },
				{ "geboorte.datum.onbekend", "geboorte.datum" },

				{ "ouders.geboorte.datum.type", "ouders.geboorte.datum" },
				{ "ouders.geboorte.datum.langFormaat", "ouders.geboorte.datum" },
				{ "ouders.geboorte.datum.datum", "ouders.geboorte.datum" },
				{ "ouders.geboorte.datum.jaar", "ouders.geboorte.datum" },
				{ "ouders.geboorte.datum.maand", "ouders.geboorte.datum" },
				{ "ouders.geboorte.datum.onbekend", "ouders.geboorte.datum" },

				{ "partners.geboorte.datum.type", "partners.geboorte.datum" },
				{ "partners.geboorte.datum.langFormaat", "partners.geboorte.datum" },
				{ "partners.geboorte.datum.datum", "partners.geboorte.datum" },
				{ "partners.geboorte.datum.jaar", "partners.geboorte.datum" },
				{ "partners.geboorte.datum.maand", "partners.geboorte.datum" },
				{ "partners.geboorte.datum.onbekend", "partners.geboorte.datum" },

				{ "kinderen.geboorte.datum.type", "kinderen.geboorte.datum" },
				{ "kinderen.geboorte.datum.langFormaat", "kinderen.geboorte.datum" },
				{ "kinderen.geboorte.datum.datum", "kinderen.geboorte.datum" },
				{ "kinderen.geboorte.datum.jaar", "kinderen.geboorte.datum" },
				{ "kinderen.geboorte.datum.maand", "kinderen.geboorte.datum" },
				{ "kinderen.geboorte.datum.onbekend", "kinderen.geboorte.datum" },

				{ "overlijden.datum.type", "overlijden.datum" },
				{ "overlijden.datum.langFormaat", "overlijden.datum" },
				{ "overlijden.datum.datum", "overlijden.datum" },
				{ "overlijden.datum.jaar", "overlijden.datum" },
				{ "overlijden.datum.maand", "overlijden.datum" },
				{ "overlijden.datum.onbekend", "overlijden.datum" },

				{ "uitsluitingKiesrecht.einddatum.type", "uitsluitingKiesrecht.einddatum" },
				{ "uitsluitingKiesrecht.einddatum.langFormaat", "uitsluitingKiesrecht.einddatum" },
				{ "uitsluitingKiesrecht.einddatum.datum", "uitsluitingKiesrecht.einddatum" },
				{ "uitsluitingKiesrecht.einddatum.jaar", "uitsluitingKiesrecht.einddatum" },
				{ "uitsluitingKiesrecht.einddatum.maand", "uitsluitingKiesrecht.einddatum" },
				{ "uitsluitingKiesrecht.einddatum.onbekend", "uitsluitingKiesrecht.einddatum" },

				{ "europeesKiesrecht.einddatumUitsluiting.type", "europeesKiesrecht.einddatumUitsluiting" },
				{ "europeesKiesrecht.einddatumUitsluiting.langFormaat", "europeesKiesrecht.einddatumUitsluiting" },
				{ "europeesKiesrecht.einddatumUitsluiting.datum", "europeesKiesrecht.einddatumUitsluiting" },
				{ "europeesKiesrecht.einddatumUitsluiting.jaar", "europeesKiesrecht.einddatumUitsluiting" },
				{ "europeesKiesrecht.einddatumUitsluiting.maand", "europeesKiesrecht.einddatumUitsluiting" },
				{ "europeesKiesrecht.einddatumUitsluiting.onbekend", "europeesKiesrecht.einddatumUitsluiting" },

				{ "nationaliteiten.datumIngangGeldigheid.type", "nationaliteiten.datumIngangGeldigheid&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.datumIngangGeldigheid.langFormaat", "nationaliteiten.datumIngangGeldigheid&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.datumIngangGeldigheid.datum", "nationaliteiten.datumIngangGeldigheid&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.datumIngangGeldigheid.onbekend", "nationaliteiten.datumIngangGeldigheid&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.datumIngangGeldigheid.jaar", "nationaliteiten.datumIngangGeldigheid&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },
				{ "nationaliteiten.datumIngangGeldigheid.maand", "nationaliteiten.datumIngangGeldigheid&nationaliteiten.nationaliteit&nationaliteiten.aanduidingBijzonderNederlanderschap" },

				{ "verblijfplaats.datumIngangGeldigheid.type", "verblijfplaats.datumIngangGeldigheid&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumIngangGeldigheid.langFormaat", "verblijfplaats.datumIngangGeldigheid&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumIngangGeldigheid.datum", "verblijfplaats.datumIngangGeldigheid&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumIngangGeldigheid.jaar", "verblijfplaats.datumIngangGeldigheid&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumIngangGeldigheid.maand", "verblijfplaats.datumIngangGeldigheid&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumIngangGeldigheid.onbekend", "verblijfplaats.datumIngangGeldigheid&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },

				{ "verblijfplaatsBinnenland.datumIngangGeldigheid.type", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.datumIngangGeldigheid" },
				{ "verblijfplaatsBinnenland.datumIngangGeldigheid.langFormaat", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.datumIngangGeldigheid" },
				{ "verblijfplaatsBinnenland.datumIngangGeldigheid.datum", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.datumIngangGeldigheid" },
				{ "verblijfplaatsBinnenland.datumIngangGeldigheid.jaar", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.datumIngangGeldigheid" },
				{ "verblijfplaatsBinnenland.datumIngangGeldigheid.maand", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.datumIngangGeldigheid" },
				{ "verblijfplaatsBinnenland.datumIngangGeldigheid.onbekend", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.datumIngangGeldigheid" },

				{ "verblijfplaats.datumVan.type", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.datumAanvangAdresBuitenland&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumVan.langFormaat", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.datumAanvangAdresBuitenland&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumVan.datum", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.datumAanvangAdresBuitenland&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumVan.jaar", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.datumAanvangAdresBuitenland&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumVan.maand", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.datumAanvangAdresBuitenland&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.datumVan.onbekend", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.datumAanvangAdresBuitenland&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },

				{ "verblijfplaatsBinnenland.datumVan.type", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.straat" },
				{ "verblijfplaatsBinnenland.datumVan.langFormaat", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.straat" },
				{ "verblijfplaatsBinnenland.datumVan.datum", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.straat" },
				{ "verblijfplaatsBinnenland.datumVan.jaar", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.straat" },
				{ "verblijfplaatsBinnenland.datumVan.maand", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.straat" },
				{ "verblijfplaatsBinnenland.datumVan.onbekend", "verblijfplaats.datumAanvangAdreshouding&verblijfplaats.straat" },

				{ "immigratie.datumVestigingInNederland.type", "immigratie.datumVestigingInNederland" },
				{ "immigratie.datumVestigingInNederland.langFormaat", "immigratie.datumVestigingInNederland" },
				{ "immigratie.datumVestigingInNederland.datum", "immigratie.datumVestigingInNederland" },
				{ "immigratie.datumVestigingInNederland.jaar", "immigratie.datumVestigingInNederland" },
				{ "immigratie.datumVestigingInNederland.maand", "immigratie.datumVestigingInNederland" },
				{ "immigratie.datumVestigingInNederland.onbekend", "immigratie.datumVestigingInNederland" },

				{ "verblijfstitel.datumIngang.type", "verblijfstitel.datumIngang" },
				{ "verblijfstitel.datumIngang.langFormaat", "verblijfstitel.datumIngang" },
				{ "verblijfstitel.datumIngang.datum", "verblijfstitel.datumIngang" },
				{ "verblijfstitel.datumIngang.jaar", "verblijfstitel.datumIngang" },
				{ "verblijfstitel.datumIngang.maand", "verblijfstitel.datumIngang" },
				{ "verblijfstitel.datumIngang.onbekend", "verblijfstitel.datumIngang" },

				{ "verblijfstitel.datumEinde.type", "verblijfstitel.datumEinde" },
				{ "verblijfstitel.datumEinde.langFormaat", "verblijfstitel.datumEinde" },
				{ "verblijfstitel.datumEinde.datum", "verblijfstitel.datumEinde" },
				{ "verblijfstitel.datumEinde.jaar", "verblijfstitel.datumEinde" },
				{ "verblijfstitel.datumEinde.maand", "verblijfstitel.datumEinde" },
				{ "verblijfstitel.datumEinde.onbekend", "verblijfstitel.datumEinde" },

				{ "ouders.datumIngangFamilierechtelijkeBetrekking.type", "ouders.datumIngangFamilierechtelijkeBetrekking" },
				{ "ouders.datumIngangFamilierechtelijkeBetrekking.langFormaat", "ouders.datumIngangFamilierechtelijkeBetrekking" },
				{ "ouders.datumIngangFamilierechtelijkeBetrekking.datum", "ouders.datumIngangFamilierechtelijkeBetrekking" },
				{ "ouders.datumIngangFamilierechtelijkeBetrekking.jaar", "ouders.datumIngangFamilierechtelijkeBetrekking" },
				{ "ouders.datumIngangFamilierechtelijkeBetrekking.maand", "ouders.datumIngangFamilierechtelijkeBetrekking" },
				{ "ouders.datumIngangFamilierechtelijkeBetrekking.onbekend", "ouders.datumIngangFamilierechtelijkeBetrekking" },

				{ "partners.aangaanHuwelijkPartnerschap.datum.type", "partners.aangaanHuwelijkPartnerschap.datum" },
				{ "partners.aangaanHuwelijkPartnerschap.datum.langFormaat", "partners.aangaanHuwelijkPartnerschap.datum" },
				{ "partners.aangaanHuwelijkPartnerschap.datum.datum", "partners.aangaanHuwelijkPartnerschap.datum" },
				{ "partners.aangaanHuwelijkPartnerschap.datum.jaar", "partners.aangaanHuwelijkPartnerschap.datum" },
				{ "partners.aangaanHuwelijkPartnerschap.datum.maand", "partners.aangaanHuwelijkPartnerschap.datum" },
				{ "partners.aangaanHuwelijkPartnerschap.datum.onbekend", "partners.aangaanHuwelijkPartnerschap.datum" },

				{ "partners.ontbindingHuwelijkPartnerschap.datum.type", "partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "partners.ontbindingHuwelijkPartnerschap.datum.langFormaat", "partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "partners.ontbindingHuwelijkPartnerschap.datum.datum", "partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "partners.ontbindingHuwelijkPartnerschap.datum.jaar", "partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "partners.ontbindingHuwelijkPartnerschap.datum.maand", "partners.ontbindingHuwelijkPartnerschap.datum" },
				{ "partners.ontbindingHuwelijkPartnerschap.datum.onbekend", "partners.ontbindingHuwelijkPartnerschap.datum" },

				// WAARDE TABELLEN
				{ "geslacht.code", "geslacht" },
				{ "geslacht.omschrijving", "geslacht" },
				{ "gemeenteVanInschrijving.code", "gemeenteVanInschrijving" },
				{ "gemeenteVanInschrijving.omschrijving", "gemeenteVanInschrijving" },
				{ "rni.deelnemer.code", "rni.deelnemer" },
				{ "rni.deelnemer.omschrijving", "rni.deelnemer" },
				{ "naam.adellijkeTitelPredicaat.code", "naam.adellijkeTitelPredicaat" },
				{ "naam.adellijkeTitelPredicaat.omschrijving", "naam.adellijkeTitelPredicaat" },
				{ "naam.adellijkeTitelPredicaat.soort", "naam.adellijkeTitelPredicaat" },
				{ "verblijfplaats.functieAdres.code", "verblijfplaats.functieAdres&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaats.functieAdres.omschrijving", "verblijfplaats.functieAdres&verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.land" },
				{ "verblijfplaatsBinnenland.functieAdres.code", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.functieAdres" },
				{ "verblijfplaatsBinnenland.functieAdres.omschrijving", "verblijfplaats.straat&verblijfplaats.locatiebeschrijving&verblijfplaats.functieAdres" },
				{ "geboorte.land.code", "geboorte.land" },
				{ "geboorte.land.omschrijving", "geboorte.land" },
				{ "geboorte.plaats.code", "geboorte.plaats" },
				{ "geboorte.plaats.omschrijving", "geboorte.plaats" },
				{ "indicatieGezagMinderjarige.code", "indicatieGezagMinderjarige" },
				{ "indicatieGezagMinderjarige.omschrijving", "indicatieGezagMinderjarige" },
				{ "europeesKiesrecht.aanduiding.code", "europeesKiesrecht.aanduiding" },
				{ "europeesKiesrecht.aanduiding.omschrijving", "europeesKiesrecht.aanduiding" },
				{ "naam.aanduidingNaamgebruik.code", "naam.aanduidingNaamgebruik" },
				{ "naam.aanduidingNaamgebruik.omschrijving", "naam.aanduidingNaamgebruik" },
				{ "kinderen.naam.adellijkeTitelPredicaat.code", "kinderen.naam.adellijkeTitelPredicaat" },
				{ "kinderen.naam.adellijkeTitelPredicaat.omschrijving", "kinderen.naam.adellijkeTitelPredicaat" },
				{ "kinderen.naam.adellijkeTitelPredicaat.soort", "kinderen.naam.adellijkeTitelPredicaat" },
				{ "kinderen.geboorte.land.code", "kinderen.geboorte.land" },
				{ "kinderen.geboorte.land.omschrijving", "kinderen.geboorte.land" },
				{ "kinderen.geboorte.plaats.code", "kinderen.geboorte.plaats" },
				{ "kinderen.geboorte.plaats.omschrijving", "kinderen.geboorte.plaats" },
				{ "ouders.geslacht.code", "ouders.geslacht" },
				{ "ouders.geslacht.omschrijving", "ouders.geslacht" },
				{ "ouders.naam.adellijkeTitelPredicaat.code", "ouders.naam.adellijkeTitelPredicaat" },
				{ "ouders.naam.adellijkeTitelPredicaat.omschrijving", "ouders.naam.adellijkeTitelPredicaat" },
				{ "ouders.naam.adellijkeTitelPredicaat.soort", "ouders.naam.adellijkeTitelPredicaat" },
				{ "ouders.geboorte.land.code", "ouders.geboorte.land" },
				{ "ouders.geboorte.land.omschrijving", "ouders.geboorte.land" },
				{ "ouders.geboorte.plaats.code", "ouders.geboorte.plaats" },
				{ "ouders.geboorte.plaats.omschrijving", "ouders.geboorte.plaats" },
				{ "partners.naam.adellijkeTitelPredicaat.code", "partners.naam.adellijkeTitelPredicaat" },
				{ "partners.naam.adellijkeTitelPredicaat.omschrijving", "partners.naam.adellijkeTitelPredicaat" },
				{ "partners.naam.adellijkeTitelPredicaat.soort", "partners.naam.adellijkeTitelPredicaat" },
				{ "partners.geboorte.land.code", "partners.geboorte.land" },
				{ "partners.geboorte.land.omschrijving", "partners.geboorte.land" },
				{ "partners.geboorte.plaats.code", "partners.geboorte.plaats" },
				{ "partners.geboorte.plaats.omschrijving", "partners.geboorte.plaats" },
				{ "partners.geslacht.code", "partners.geslacht" },
				{ "partners.geslacht.omschrijving", "partners.geslacht" },
				{ "partners.soortVerbintenis.code", "partners.soortVerbintenis" },
				{ "partners.soortVerbintenis.omschrijving", "partners.soortVerbintenis" },
				{ "partners.aangaanHuwelijkPartnerschap.land.code", "partners.aangaanHuwelijkPartnerschap.land" },
				{ "partners.aangaanHuwelijkPartnerschap.land.omschrijving", "partners.aangaanHuwelijkPartnerschap.land" },
				{ "partners.aangaanHuwelijkPartnerschap.plaats.code", "partners.aangaanHuwelijkPartnerschap.plaats" },
				{ "partners.aangaanHuwelijkPartnerschap.plaats.omschrijving", "partners.aangaanHuwelijkPartnerschap.plaats" },
				{ "overlijden.land.code", "overlijden.land" },
				{ "overlijden.land.omschrijving", "overlijden.land" },
				{ "overlijden.plaats.code", "overlijden.plaats" },
				{ "overlijden.plaats.omschrijving", "overlijden.plaats" },
				{ "immigratie.landVanwaarIngeschreven.code", "immigratie.landVanwaarIngeschreven" },
				{ "immigratie.landVanwaarIngeschreven.omschrijving", "immigratie.landVanwaarIngeschreven" },
				{ "verblijfstitel.aanduiding.code", "verblijfstitel.aanduiding" },
				{ "verblijfstitel.aanduiding.omschrijving", "verblijfstitel.aanduiding" },

				// GEZAG TABELLEN
				{ "gezag.type", "gezag" },
				{ "gezag.ouder", "gezag" },
				{ "gezag.ouder.burgerservicenummer", "gezag" },
				{ "gezag.ouders", "gezag" },
				{ "gezag.ouders.burgerservicenummer", "gezag" },
				{ "gezag.derde", "gezag" },
				{ "gezag.derde.burgerservicenummer", "gezag" },
				{ "gezag.derden", "gezag" },
				{ "gezag.derden.burgerservicenummer", "gezag" },
				{ "gezag.minderjarige", "gezag" },
				{ "gezag.minderjarige.burgerservicenummer", "gezag" }
			}
		};
	}
}
