openapi: 3.0.3
info:
  title: Geboorte definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaGeboorte:
      allOf:
        - $ref: 'brp/geboorte/geboorte-basis-v1.yaml#/components/schemas/GeboorteBasis'
        - type: object
          properties:
            land:
              $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
            plaats:
              $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
