openapi: 3.1.0
info:
  title: Gezag definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaGezagPersoonBeperkt:
      allOf:
        - $ref: 'persoon-v1.yaml#/components/schemas/GbaPersoonBeperkt'
        - type: object
          properties:
            gezag:
              $ref: "#/components/schemas/Gezag"

    Gezag:
      type: array
      items: 
        $ref: 'brp/gezag/gezagsrelatie-v2.yaml#/components/schemas/Gezagsrelatie'
      minItems: 0
