openapi: 3.0.3
info:
  title: Immigratie definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaImmigratie:
      type: object
      description: |
        Gegevens over het het immigratie van een persoon.
          * **landVanWaarIngeschreven** : het land waar de persoon woonde voor (her)vestiging in Nederland.
      properties:
        datumVestigingInNederland:
          $ref: 'brp/datum-v1.yaml#/components/schemas/GbaDatum'
        landVanwaarIngeschreven:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
