openapi: 3.0.3
info:
  title: Kind definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaKind:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        inOnderzoek:
          $ref: 'brp/in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        naam:
          $ref: 'brp/naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/GbaGeboorte'
