openapi: 3.0.3
info:
  title: Nationaliteit definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaNationaliteit:
      type: object
      properties:
        aanduidingBijzonderNederlanderschap:
          type: string
          pattern: ^(B|V)$
        datumIngangGeldigheid:
          $ref: 'brp/datum-v1.yaml#/components/schemas/GbaDatum'
        nationaliteit:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        redenOpname:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
            $ref: 'brp/in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
