openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    OuderAanduiding:
      type: string
      pattern: ^[1|2]$
      example: "1"
    GbaOuder:
      type: object
      description: |
        Gegevens over de ouder van de persoon.
        * **datumIngangFamilierechtelijkeBetrekking** - De datum waarop de familierechtelijke betrekking is ontstaan.
      properties:
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        geslacht:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        ouderAanduiding:
          $ref: '#/components/schemas/OuderAanduiding'
        datumIngangFamilierechtelijkeBetrekking:
          $ref: 'brp/datum-v1.yaml#/components/schemas/GbaDatum'
        naam:
          $ref: 'brp/naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
        inOnderzoek:
          $ref: 'brp/in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/GbaGeboorte'
