openapi: 3.0.3
info:
  title: Overlijden definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaOverlijden:
        type: object
        properties:
          datum:
            $ref: 'brp/datum-v1.yaml#/components/schemas/GbaDatum'
          land:
            $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
          plaats:
            $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
          inOnderzoek:
            $ref: 'brp/in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
