openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaPartner:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        geslacht:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        soortVerbintenis:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        naam:
          $ref: 'brp/naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/GbaGeboorte'
        inOnderzoek:
          $ref: 'brp/in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        aangaanHuwelijkPartnerschap:
          $ref: '#/components/schemas/GbaAangaanHuwelijkPartnerschap'
        ontbindingHuwelijkPartnerschap:
          $ref: "#/components/schemas/GbaOntbindingHuwelijkPartnerschap"
    GbaAangaanHuwelijkPartnerschap:
      type: object
      description: |
        Gegevens over de voltrekking van het huwelijk of het aangaan van het geregistreerd partnerschap.
        * **datum** - De datum waarop het huwelijk is voltrokken of het partnerschap is aangegaan.
        * **land** - Het land waar het huwelijk is voltrokken of het partnerschap is aangegaan. Wordt gevuld met waarden uit de landelijke tabel 'Landen'.
        * **plaats** - De gemeente waar het huwelijk is voltrokken of het partnerschap is aangegaan. Wordt gevuld met waarden uit de landelijke tabel "Gemeenten" voor een gemeente in Nederland of de omschrijving van een buitenlandse plaats.
      properties:
        datum:
          $ref: 'brp/datum-v1.yaml#/components/schemas/GbaDatum'
        land:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        plaats:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
    GbaOntbindingHuwelijkPartnerschap:
      type: object
      properties:
        datum:
          $ref: 'brp/datum-v1.yaml#/components/schemas/GbaDatum'
