openapi: 3.0.3
info:
  title: Persoon definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaPersoonBeperkt:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        geboorte:
          $ref: 'brp/geboorte/geboorte-basis-v1.yaml#/components/schemas/GeboorteBasis'
        geheimhoudingPersoonsgegevens:
          $ref: 'brp/geheim/indicatie-geheim-v1.yaml#/components/schemas/IndicatieGeheim'
        geslacht:
          $ref: 'brp/geslacht/geslachtsaanduiding-v1.yaml#/components/schemas/Geslachtsaanduiding'
        persoonInOnderzoek:
          $ref: 'brp/in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        naam:
          $ref: 'brp/naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
        opschortingBijhouding:
          $ref: 'brp/opschorting-bijhouding/opschorting-bijhouding-v1.yaml#/components/schemas/GbaOpschortingBijhouding'
        gemeenteVanInschrijving:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        verblijfplaats:
          $ref: 'brp/verblijfplaats/verblijfplaats-beperkt-v1.yaml#/components/schemas/GbaVerblijfplaatsBeperkt'
        rni:
          type: array
          items:
            $ref: 'brp/rni/rni-deelnemer-v1.yaml#/components/schemas/RniDeelnemer'
        verificatie:
          $ref: 'brp/verificatie/verificatie-v1.yaml#/components/schemas/GbaVerificatie'
    GbaPersoon:
      type: object
      properties:
        aNummer:
          $ref: 'brp/identificatienummers/anummer-v1.yaml#/components/schemas/ANummer'
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        datumEersteInschrijvingGBA:
          $ref: 'brp/datum-v1.yaml#/components/schemas/GbaDatum'
        geheimhoudingPersoonsgegevens:
          $ref: 'brp/geheim/indicatie-geheim-v1.yaml#/components/schemas/IndicatieGeheim'
        geslacht:
          $ref: 'brp/geslacht/geslachtsaanduiding-v1.yaml#/components/schemas/Geslachtsaanduiding'
        persoonInOnderzoek:
          $ref: 'brp/in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        gezagInOnderzoek:
          $ref: 'brp/in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        uitsluitingKiesrecht:
          $ref: 'brp/kiesrecht/uitsluiting-kiesrecht-v1.yaml#/components/schemas/GbaUitsluitingKiesrecht'
        europeesKiesrecht:
          $ref: 'brp/kiesrecht/europees-kiesrecht-v1.yaml#/components/schemas/GbaEuropeesKiesrecht'
        naam:
          $ref: 'brp/naam/naam-v1.yaml#/components/schemas/GbaNaamPersoon'
        nationaliteiten:
          type: array
          items:
            $ref: 'brp/nationaliteit/nationaliteit-v1.yaml#/components/schemas/GbaNationaliteit'
        geboorte:
          $ref: 'brp/geboorte/geboorte-v1.yaml#/components/schemas/GbaGeboorte'
        opschortingBijhouding:
          $ref: 'brp/opschorting-bijhouding/opschorting-bijhouding-v1.yaml#/components/schemas/GbaOpschortingBijhouding'
        overlijden:
          $ref: 'brp/overlijden/overlijden-v1.yaml#/components/schemas/GbaOverlijden'
        verblijfplaats:
          $ref: 'brp/verblijfplaats/verblijfplaats-v1.yaml#/components/schemas/GbaVerblijfplaats'
        immigratie:
          $ref: 'brp/immigratie/immigratie-v1.yaml#/components/schemas/GbaImmigratie'
        gemeenteVanInschrijving:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        datumInschrijvingInGemeente:
          $ref: 'brp/datum-v1.yaml#/components/schemas/GbaDatum'
        indicatieCurateleRegister:
          $ref: 'brp/indicatie-curatele-register-v1.yaml#/components/schemas/IndicatieCurateleRegister'
        indicatieGezagMinderjarige:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
          deprecated: true
        gezag:
          $ref: 'gezag.yaml#/components/schemas/Gezag'
        verblijfstitel:
          $ref: 'brp/verblijfstitel/verblijfstitel-v1.yaml#/components/schemas/GbaVerblijfstitel'
        kinderen:
          type: array
          items:
            $ref: 'brp/kind/kind-v1.yaml#/components/schemas/GbaKind'
        ouders:
          type: array
          items:
            $ref: 'brp/ouder/ouder-v1.yaml#/components/schemas/GbaOuder'
        partners:
          type: array
          items:
            $ref: 'brp/partner/partner-v1.yaml#/components/schemas/GbaPartner'
        rni:
          type: array
          items:
            $ref: 'brp/rni/rni-deelnemer-v1.yaml#/components/schemas/RniDeelnemer'
        verificatie:
          $ref: 'brp/verificatie/verificatie-v1.yaml#/components/schemas/GbaVerificatie'
