openapi: 3.1.0
info:
  title: personen query response type definitie
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    PersonenQueryResponse:
      type: object
      required:
        - type
      discriminator:
        propertyName: type
        mapping:
          ZoekMetGeslachtsnaamEnGeboortedatum: '#/components/schemas/ZoekMetGeslachtsnaamEnGeboortedatumResponse'
          ZoekMetNaamEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetNaamEnGemeenteVanInschrijvingResponse'
          RaadpleegMetBurgerservicenummer: '#/components/schemas/RaadpleegMetBurgerservicenummerResponse'
          ZoekMetPostcodeEnHuisnummer: '#/components/schemas/ZoekMetPostcodeEnHuisnummerResponse'
          ZoekMetStraatHuisnummerEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetStraatHuisnummerEnGemeenteVanInschrijvingResponse'
          ZoekMetNummeraanduidingIdentificatie: '#/components/schemas/ZoekMetNummeraanduidingIdentificatieResponse'
          ZoekMetAdresseerbaarObjectIdentificatie: '#/components/schemas/ZoekMetAdresseerbaarObjectIdentificatieResponse'
      properties:
        type:
          type: string
    RaadpleegMetBurgerservicenummerResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/GbaPersoon'
    ZoekMetGeslachtsnaamEnGeboortedatumResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon-v1.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetNaamEnGemeenteVanInschrijvingResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon-v1.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetPostcodeEnHuisnummerResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon-v1.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetStraatHuisnummerEnGemeenteVanInschrijvingResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon-v1.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetNummeraanduidingIdentificatieResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon-v1.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetAdresseerbaarObjectIdentificatieResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'gezag.yaml#/components/schemas/GbaGezagPersoonBeperkt'
