version: '3.4'

services:

  identityserver:
    container_name: identityserver
    image: ghcr.io/brp-api/idp-mock:latest
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
      platforms:
        - linux/amd64

  brp.autorisatie.proxy:
    container_name: brp-autorisatie
    image: ghcr.io/brp-api/brp-autorisatie-protocollering:latest
    build:
      context: .
      dockerfile: Brp.AutorisatieEnProtocollering.Proxy/Dockerfile
      platforms:
        - linux/amd64

  brp.referentie.api:
    container_name: brp-referentie-api
    image: ghcr.io/brp-api/brp-referentie-api:latest
    build:
      context: .
      dockerfile: Brp.Referentie.Api/Dockerfile
