services:
  personen-data-service:
    container_name: personen-data-service
    image: ghcr.io/brp-api/personen-data-service:latest
    build:
      context: .
      dockerfile: Personen.Data.Service/Dockerfile

  gezagmock:
    container_name: gezagmock
    image: ghcr.io/brp-api/gezag-mock:latest
    build:
      context: .
      dockerfile: GezagMock/Dockerfile
