name: continuous integration

on:
  push:
    paths:
      - src/**
      - features/**
      - .github/workflows/ci.yml
      - .docker/personen-data-service.yml
  workflow_dispatch:
    inputs:
      publishType:
        description: wat moet worden gereleased?
        required: true
        default: ''
        type: choice
        options:
          - ci-only
          - gezag-proxy-mock
          - gezag-mock

env:
  NODE_VERSION: '20'
  DOTNET_SOLUTION_FILE_PATH: src/PersonenDataService.sln
  GEZAG_MOCK_PROJECT_PATH: ./src/GezagMock
  GEZAG_MOCK_CSPROJ_FILE_PATH: ./src/GezagMock/GezagMock.csproj
  GEZAG_MOCK_CONTAINER_IMAGE: ghcr.io/brp-api/gezag-mock
  GEZAG_PROXY_MOCK_PROJECT_PATH: ./src/GezagProxyMock
  GEZAG_PROXY_MOCK_CSPROJ_FILE_PATH: ./src/GezagProxyMock/GezagProxyMock.csproj
  GEZAG_PROXY_MOCK_CONTAINER_IMAGE: ghcr.io/brp-api/gezag-proxy-mock
  DATA_SERVICE_DOCKER_FILE_PATH: .docker/personen-data-service.yml

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Genereer build run identifier
        id: build-run-id
        uses: ./.github/actions/genereer-build-run-identifier

      - name: Zet versie met build run in Gezag mock csproj
        uses: ./.github/actions/zet-versie-met-build-run-in-csproj
        id: app-version
        with:
          path-csproj-file: ${{ env.GEZAG_MOCK_CSPROJ_FILE_PATH }}
          build-run: ${{ steps.build-run-id.outputs.build-run }}
      - name: Zet versie met build run in Gezag Proxy mock csproj
        uses: ./.github/actions/zet-versie-met-build-run-in-csproj
        id: mock-version
        with:
          path-csproj-file: ${{ env.GEZAG_PROXY_MOCK_CSPROJ_FILE_PATH }}
          build-run: ${{ steps.build-run-id.outputs.build-run }}

      - name: Haal data service build run identifier uit Docker manifest
        id: data-service-build-run-id
        uses: ./.github/actions/haal-build-run-identifier-uit-docker-manifest
        with:
          path-docker-manifest: ${{ env.DATA_SERVICE_DOCKER_FILE_PATH }}
      - name: Haal data service versie uit Docker manifest
        id: data-service-version
        uses: ./.github/actions/haal-versie-uit-docker-manifest
        with:
          path-docker-manifest: ${{ env.DATA_SERVICE_DOCKER_FILE_PATH }}

      - name: Valideer .NET solution
        uses: ./.github/actions/valideer-dotnet-solution
        with:
          path-solution-file: ${{ env.DOTNET_SOLUTION_FILE_PATH }} 
  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci

      - name: Zet run permissions op script folder
        uses: ./.github/actions/zet-run-bash-scripts-permission
        with:
          path-bash-file-or-folder: ./scripts/*

      - name: Start containers
        run: |
          ./scripts/containers-start.sh ci
      - name: Wait for DB restart
        run: sleep 5s
        shell: bash
      - name: Valideer functionele specs
        run: |
          ./scripts/specs-verify.sh
      - name: Stop containers
        if: always()
        run: |
          ./scripts/containers-stop.sh ci

      - name: Genereer test rapportage
        if: always()
        run: |
          node ./scripts/generate-cucumber-reports.js ${{ steps.data-service-version.outputs.version }} ${{ steps.data-service-build-run-id.outputs.build-run }} ${{ github.ref_name }}
      - name: Upload test rapportage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: |
            test-reports
            test-data/logs
      - name: Push test rapportage naar brp-api.github.io repo
        if: always()
        uses: tech-thinker/push-to-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_PAT_TOKEN }}
        with:
          source-directory: test-reports/cucumber-js/reports
          destination-repository-name: brp-api.github.io
          destination-github-username: BRP-API
          target-branch: test-reports/personen
          commit-message: "test rapporten van build: ${{ steps.data-service-build-run-id.outputs.build-run }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Configureer container image builder voor multi-platform
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          driver: docker-container

      - name: Build en push gezag mock container images naar registry
        if: always() && inputs.publishType == 'gezag-mock'
        uses: docker/build-push-action@v6
        with:
          file: src/GezagMock/Dockerfile
          context: src
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ${{ env.GEZAG_MOCK_CONTAINER_IMAGE }}:latest
            ${{ env.GEZAG_MOCK_CONTAINER_IMAGE }}:${{ steps.app-version.outputs.version }}-latest
            ${{ env.GEZAG_MOCK_CONTAINER_IMAGE }}:${{ steps.app-version.outputs.version }}-${{ steps.build-run-id.outputs.build-run }}

      - name: Build en push gezag proxy mock container images naar registry
        if: always() && inputs.publishType == 'gezag-proxy-mock'
        uses: docker/build-push-action@v6
        with:
          file: src/GezagProxyMock/Dockerfile
          context: src
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ${{ env.GEZAG_PROXY_MOCK_CONTAINER_IMAGE }}:latest
            ${{ env.GEZAG_PROXY_MOCK_CONTAINER_IMAGE }}:${{ steps.mock-version.outputs.version }}-latest
            ${{ env.GEZAG_PROXY_MOCK_CONTAINER_IMAGE }}:${{ steps.mock-version.outputs.version }}-${{ steps.build-run-id.outputs.build-run }}
